name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        include-prerelease: true
    - name: build Little CMS
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        msbuild /p:Configuration=Release;Platform=x64 lcms2\Projects\VC2022\lcms2_static\lcms2_static.vcxproj
    - name: fetch nuget cache
      id: cache-nuget
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: build tool
      shell: cmd
      run: |
        cd MHC2Gen
        dotnet publish -c Release -r win-x64 -p:UseNativeAot=true -o bin\aot
        tar caf MHC2Gen.zip -C bin\aot MHC2Gen.exe
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: bin
        # Directory containing files to upload
        path: bin
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: obj
        # Directory containing files to upload
        path: obj
    - name: prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "ci-build"
        prerelease: true
        title: "Latest Development Build"
        files: |
          MHC2Gen.zip
